### ISSUE TITLE
Error building for macOS 10.15

### ISSUE THREAD

**Issue by alexanderwe** [pointfreeco/swift-parsing#242] opened 2022-07-10 15:22 UTC
I am currently trying to integrate one of my libraries(https://github.com/alexanderwe/ConventionalCommitsKit), which uses `swift-parsing` into one a CLI for macOS `10.15`. As soon as I integrate my library into the CLI project I get the following compilation error, when I run `swift build`.

```
error: the library '_URLRouting' requires macos 10.10, but depends on the product 'XCTestDynamicOverlay' which requires macos 10.15; consider changing the library '_URLRouting' to require macos 10.15 or later, or the product 'XCTestDynamicOverlay' to require macos 10.10 or earlier.
```

When I build via Xcode everything works as well as when I build my library alone (with `swift build`) but inside the CLI project I get this compilation error when compiling with `swift build`. Do you have any idea why `_URLRouting` needs to have macOS `10.10` ? 

This is the Package.swift for my CLI project so far:

```swift
// swift-tools-version:5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "MyCLI",
    platforms: [.macOS("10.15")],
    products: [
       .executable(name: "mycli", targets: ["MyCLI"]),
   ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-argument-parser", exact: "1.1.0"),
        .package(url: "https://github.com/alexanderwe/ConventionalCommitsKit.git", from: "1.0.1")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .executableTarget(
            name: "MyCLI",
            dependencies: [
		.target(name: "Commands")
            ]
        ),
        .target(
            name: "Commands",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
                .product(name: "ConventionalCommitsKit", package: "ConventionalCommitsKit")
            ]
        ),
	.target(name: "Core")
    ]
)
```

I have the feeling I oversee something fundamental here - but I cannot figure it unfortunately

**Comment by stephencelis** [comment] 2022-08-15 18:53
@alexanderwe Sorry for the delay, but have you tried our official package?

https://github.com/pointfreeco/swift-url-routing

The `_URLRouting` package that is shipped directly in this library was a beta and is out-of-date.

It is possible we have our platform requirements stricter than they need to be, and we'd definitely be down to discuss changes!

**Comment by stephencelis** [comment] 2023-04-04 15:53
Going to close this since it hasn't been replied to in awhile, but if you believe you've found a bug, please open a new issue with a way to reproduce, or if you'd like to ask a question, please start a discussion.

**Closed by stephencelis** 2023-04-04 15:53 UTC

**Comment by alexanderwe** [comment] 2023-04-04 16:09
Hey @stephencelis I am so sorry.. I totally forgot to reply to this issue and basically forgot it exists. I stopped working on that project that caused this error. If I would still see this error in the latest version I will create a new issue but I doubt it. 

Sorry for any inconveniences caused by not answering

**Comment by stephencelis** [comment] 2023-04-04 16:15
No worries at all. We know how it is :smile: Hopefully the issue is resolved in the current version.
